services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"      # Основной порт для AMQP протокола
      - "15672:15672"    # Порт для веб-интерфейса управления
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq

  movie-service:
    build:
      context: ./movie_service
    ports:
      - "8002:8000"
    depends_on:
      - db
      - rabbitmq

  recommendation-service:
    build:
      context: ./recommendation_service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - rabbitmq
      - movie-service

volumes:
  db_data:
